apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: anchore-engine
  name: anchore-engine-core
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: anchore-engine
        component: core
    spec:
      containers:
      - env:
        - name: ANCHORE_DB
          value: anchore
        - name: ANCHORE_DB_HOST
          value: anchore-db:5432
        - name: ANCHORE_IO_USER
          valueFrom:
            secretKeyRef:
              key: anchoreIOUser
              name: anchore-engine
        - name: ANCHORE_IO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: anchoreIOPassword
              name: anchore-engine
        - name: ANCHORE_DB_USER
          valueFrom:
            secretKeyRef:
              key: dbUser
              name: anchore-engine
        - name: ANCHORE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: dbPassword
              name: anchore-engine
        - name: ANCHORE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: adminPassword
              name: anchore-engine
        - name: ANCHORE_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ANCHORE_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ANCHORE_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: docker.io/anchore/anchore-engine:v0.2.3
        imagePullPolicy: IfNotPresent
        resources:
            limits:
              memory: 1024Mi
            requests:
              memory: 256Mi
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: external-api
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: anchore-engine-core
        ports:
        - containerPort: 8228
          name: external-api
          protocol: TCP
        - containerPort: 8083
          name: queue-service
          protocol: TCP
        - containerPort: 8338
          name: webhook-service
          protocol: TCP
        - containerPort: 8082
          name: catalog
          protocol: TCP
        - containerPort: 8087
          name: policy-engine
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: external-api
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: anchore-engine-core
        name: config-volume
