apiVersion: v1
kind: Service
metadata:
  labels:
    app: anchore-engine
  name: anchore-engine
spec:
  ports:
  - name: anchore-external-api
    port: 8228
    protocol: TCP
    targetPort: 8228
  - name: anchore-kubewebhook
    port: 8338
    protocol: TCP
    targetPort: 8338
  - name: anchore-queue
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: anchore-catalog
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: anchore-policy
    port: 8087
    protocol: TCP
    targetPort: 8087
  selector:
    app: anchore-engine
    component: core
  sessionAffinity: None
  type: ClusterIP
