apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql-persistent
    template: postgresql-persistent-template
  name: anchore-db
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: anchore-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
